name: flutter_helloworld
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # This library is to used to set app icons.
  # FYI: https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  image_path: "assets/icon.png"
